{
    'name': 'HR Custody',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': """Manage the company properties""",
    'description': 'Manage the company properties when it is in '
                   'the custody of an employee',
    'author': 'Kaizen Principles',
    'company': 'Kaizen Principles',
    'maintainer': 'Kaizen Principles',
    'website': "https://www.kaizenae.com",
    'depends': ['hr',
                'mail',
                'hr_employee_updation',
                'product'],
    'data': [
        'security/custody_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'wizard/property_return_reason_views.xml',
        'wizard/property_return_date_views.xml',
        'views/hr_custody_views.xml',
        'views/custody_property_views.xml',
        'views/hr_employee_views.xml',
        'report/report_custody_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
