version: '3.8'

services:
  web:
    image: odoo:18.0
    container_name: kuec_odoo18
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      # Mapped the entire KUEC project directory to extra-addons
      # This will include the kuec_service_catalogue module
      - ./:/mnt/extra-addons
      # Core Odoo 18 addons path from host
      - E:\Self\18\odoo18\addons:/mnt/odoo18-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: >
      odoo -u kuec_service_catalogue -d kuec --addons-path=/mnt/extra-addons,/mnt/odoo18-addons,/usr/lib/python3/dist-packages/odoo/addons --without-demo=all --limit-time-cpu=6000 --limit-time-real=6000

  db:
    image: postgres:15
    container_name: kuec_postgres15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
