# -*- coding: utf-8 -*-
from . import res_partner_bank
from . import product_template
from . import company_size
from . import vendor_evaluation_conf
from . import vendor_evaluation_conf_line
from . import res_partner
from . import worked_company
from . import iso_certification
from . import vendor_otp
from . import res_company
from . import res_config_settings
from . import tender_rfq_document
from . import rfq_line_mixin
from . import tender_bafo_request
from . import tender_rfq_line
from . import vendor_evaluation
from . import vendor_evaluation_line
from . import tender_bid_rfq_line
from . import tender_bid_approval
from . import tender_required_attachment
from . import tender_bid_required_attachment
from . import evaluation_checklist_conf
from . import evaluation_checklist_conf_line
from . import evaluation_checklist
from . import tender_bid
from . import tender_checklist_conf
from . import tender_checklist
from . import tender_rfq
from . import rq_type_attachment_line
from . import purchase_requisition_type
from . import material_attachment_line
from . import material_purchase_requisition
from . import purchase_order
from . import purchase_contract_agreement_line
from . import purchase_contract_agreement
from . import purchase_requisition
