# -*- coding: utf-8 -*-
{
    'name': "Performance Management",
    'version': '0.5',
    'category': 'Services',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'pragtech.co.in',
    'summary': "Pragtech HRMS Performance Management",
    'description': """The HRMS Performance Management module for Odoo is designed to streamline and digitize employee 
    performance evaluation processes across the organization. This module facilitates structured Goal Setting, 
    KPI and KRA Management, Self and Manager Evaluations, 360-Degree Feedback, and HR Final Approvals, all within a centralized system.""",
    'depends': ['base', 'hr'],
    'data': [
        'data/my_goals_cron.xml',
        'security/hrms_perfomance_security.xml',
        'security/ir.model.access.csv',
        'views/kra.xml',
        'views/kpi.xml',
        'views/my_goal.xml',
        'views/goals_assignment.xml',
        'views/hr_employee.xml',
        'views/performance_feedback.xml',
        'views/evalution_view.xml',
        'views/feedback_360_view.xml',
        'views/employee_warning_view.xml',
    ],
    'images': ['static/description/HRMS_Performance_Management.gif'],
    'live_test_url': 'http://www.pragtech.co.in/company/proposal-form.html?id=103&name=Performance-Management',
    'price': 60.00,
    'currency': 'USD',
    'license': 'OPL-1',
    'application': True,
    'auto_install': False,
    'installable': True,
}
