from . import kaz_cash_forecast_categories
from . import kaz_cash_forecast_tag
from . import kaz_cash_forecast_type
from . import cash_forecast_fiscal_year
from . import cash_forecast_fiscal_period
from . import kaz_cash_forecast
from . import kaz_cash_forecast_report
from . import account_account
from . import kaz_cash_flow_forecasting_dashboard
from . import res_company
from . import local_account_book
from . import res_config_settings
from . import ir_module_module
from . import onboarding
from . import onboarding_onboarding_step
from . import kaz_budget_forecast_settings
