# -*- coding: utf-8 -*-
{
    'name': 'Department Procurement',
    'version': '18.0.1.0.0',
    'category': 'Purchases',
    'summary': 'Manage material requisition of department',
    'description': """Manage material requisition of department""",
    'author': 'Kaizen Principles',
    'company': 'Kaizen Principles',
    'maintainer': 'Kaizen Principles',
    'website': 'https://www.kaizenae.com',
    'depends': ['material_purchase_requisitions',
                'kz_requisition_quintuple_approvals',
                'kaz_procurement_doa_kuec',
                'account_budget',
                'uom',
                'kaz_company_restriction_base',
                'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/email_template.xml',
        'data/cron.xml',
        'views/annual_department_procurement_plan_views.xml',
        'views/annual_department_procurement_plan_items_views.xml',
        'views/procurement_master_plan_views.xml',
        'views/hr_department_views.xml',
        'views/purchase_order_views.xml',
        'views/purchase_requisition_views.xml',
        'views/account_move_views.xml',
        'views/res_settings_views.xml',
        'views/menu.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
