{
    'name': "Master Budget",
    'version': '18.0.1.0.0',
    'category': 'Accounting',
    'summary': 'Master Budget',
    'description': """Master Budget""",
    'author': 'Kaizen Principles',
    'company': 'Kaizen Principles',
    'maintainer': 'Kaizen Principles',
    'website': 'https://www.kaizenae.com',
    'depends': [
        'kz_budget_custom',
        'kaz_company_restriction_base',
    ],
    'data': [
        'data/sequence.xml',
        'security/ir.model.access.csv',
        'views/budget_master_plan_views.xml',
        'views/budget_analytic_views.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
