# -*- coding: utf-8 -*-
from . import register_form
from . import res_company
from . import res_config_settings
from . import hr_recruitment_stage
from . import register_form_approval
from . import hr_master_plan_approval
from . import hr_applicant_approval
from . import hr_applicant
from . import hr_master_plan
from . import hr_internship_reward
from . import hr_internship_reward_approval
from . import related_party_entries
from . import related_party_entries_approval
from . import write_off_request
from . import write_off_request_approval
from . import account_move
from . import account_move_approval
from . import account_payment
from . import settlement_request_approval
from . import settlement_request
from . import petty_cash_request
from . import petty_cash_request_approval
from . import budget_analytic
from . import budget_master_plan
from . import budget_master_plan_approval
from . import credit_card_request
from . import credit_card_request_approval
from . import account_asset_depreciation
from . import account_asset_depreciation_approval
from . import account_asset
from . import employee_promotion
from . import employee_promotion_approval
from . import lease_lessee_contract
from . import lease_lessee_contract_approval
from . import lease_lessor_contract
from . import lease_lessor_contract_approval
