from . import hr_staffing_plan
from . import res_company
from . import res_settings
from . import res_users
from . import ir_actions_act_window
from . import off_cycle_staffing_reason
from . import hr_recruitment_requests
from . import hr_job_position_request
from . import hr_job
from . import hr_applicant
from . import hr_master_staffing_plan
from . import hr_employee
from . import budget_line
