# -*- coding: utf-8 -*-
{
    'name': 'KUEC Service Catalogue',
    'version': '18.0.2.13.0',
    'category': 'Sales',
    'summary': 'Service Catalogue & Business Configurability',
    'description': """
    KUEC Service Catalogue module containing core settings, required documents, and Wink tab scaffolding.
    Epic 1 implementation.
    """,
    'author': 'Kaizen Options',
    'depends': [
        'kuec_portal_foundation',
        'sale_management',
        'sale_subscription',
        'project',
        'portal',
        'account',
        'payment',
        'hr',
        'web',
        'sale_project',
        'purchase',
        'rating',
        'helpdesk',
    ],
    'data': [
        'security/kuec_service_catalogue_security.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'data/sale_config_parameter.xml',
        'data/kuec_classification_data.xml',
        'data/kuec_tag_data.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'data/kuec_payment_terms_data.xml',
        'data/mail_template_request.xml',
        'data/kuec_wallet_journal_data.xml',
        'views/kuec_classification_views.xml',
        'views/wink_bundle_views.xml',
        'views/kuec_service_faq_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/sale_order_views.xml',
        'views/kuec_reports.xml',
        'views/coordinator_menu.xml',
        'views/portal_components.xml',
        'views/website_templates/employee_portal_templates.xml',
        'views/website_templates/request_templates.xml',
        'views/kuec_employee_directory_views.xml',
        'views/project_stage_views.xml',
        'views/sale_subscription_pricing_views.xml',
        'wizard/wink_assign_vendor_wizard_views.xml',
        'wizard/wink_add_services_wizard_views.xml',
        'wizard/wink_finalize_wizard_views.xml',
        'views/project_task_views.xml',
        'views/website_templates/wink_catalogue_page.xml',
        'views/website_templates/project_portal_templates.xml',
        'views/website_templates/wink_bundle_lifecycle_templates.xml',
        'views/website_templates/terms_templates.xml',
        'views/website_templates/kuec_terms_template.xml',
        'views/website_templates/wink_rating_templates.xml',
        'views/wink_bundle_change_log_views.xml',
        'views/kuec_wallet_views.xml',
    ],
    'demo': [
        'data/demo_data.xml',
        'data/gen_demo_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'kuec_service_catalogue/static/src/css/wink_bundle.css',
            'kuec_service_catalogue/static/src/js/wink_catalogue.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
    # ISSUE-001: Post-init hook for employee directory empty-string normalization (ORM only).
    'post_init_hook': 'post_init_hook',
}
