# -*- coding: utf-8 -*-
from . import hr_employee_base
from . import attachment_line_mixin
from . import attachment_attachment
from . import attachment_line
from . import res_partner
from . import res_users
from . import partner_attachment_line
from . import partner_checklist_conf
from . import partner_checklist
from . import partner_category
from . import res_company
from . import res_config_settings
from . import purchase_order
from . import sale_order
from . import account_move
from . import account_move_line
from . import account_payment
from . import purchase_requisition
